config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# get 'indicators', :to=>'indicators#index'

Rails.application.routes.draw do

  resources :indicators
end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  unloadable
  validates :name, presence: true
end

app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  unloadable
  def index
    @indicators=Indicator.all
  end
  def show
    @indicator=Indicator.find(params[:id])
  end

  def new
    @indicator=Indicator.new
  end
  def edit
    @indicator=Indicator.find(params[:id])
  end
  def create
    @indicator=Indicator.new(indicator_params)
    @indicator.save
    redirect_to @indicator
  end
  def update
    @indicator=Indicator.find(params[:id])
    if @indicator.update(indicator_params)
      redirect_to @indicator
    else
      render 'edit'
    end
  end
  def destroy
    @indicator=Indicator.find(params[:id])
    @indicator.destroy

    redirect_to indicators_path
  end
  private
  def indicator_params
    params.require(:indicator).permit(:name, :interpretation, :inputtype, :category,:unit, :marksperperiod, :isobjective)
  end
end

app/views/indicators/_tools.erb
<a href="/indicators/new">Add performance indicator</a>
<a href="/indicators/new">Add performance indicator</a>
<a href="/indicators/new">Add performance indicator</a>

app/views/indicators/edit.html.erb
<h2>Edit show</h2>

<div class="content">
  <div class="indicator-gener-left indicator-gener">
    <%= form_for :indicator, url: indicator_path(@indicator),method: :patch do |f| %>
        <div class="input-item">
          <p class="indicator-label"><%= f.label :"Indicator name" %>
            <span class="required">*</span>
          </p>
          <p class="indicator-input">
            <%= f.text_field :name %>
          </p>
        </div>
        <div class="input-item">
          <p class="indicator-label"><%= f.label :'Actual values input type' %>
            <span class="required">*</span>
          </p>
          <p class="indicator-input">
            <%= f.select(:inputtype) do %>
                <% [['Direct input', 0], ['Exact values from the interpretation matrix', 1]].each do |c| -%>
                    <%= content_tag(:option, c.first, value: c.last) %>
                <% end %>
            <% end %>
          </p>
        </div>
        <div class="input-item">
          <p class="indicator-label"><%= f.label :'Category' %>
            <span class="required">*</span>
          </p>
          <p class="indicator-input">
            <%= f.select(:category) do %>
                <% [['Common indicator', 0]].each do |c| -%>
                    <%= content_tag(:option, c.first, value: c.last) %>
                <% end %>
            <% end %>
          </p>
        </div>
        <div class="input-item">
          <p class="indicator-label"><%= f.label :'Indicator unit of measurement ' %>
            <span class="required">*</span>
          </p>
          <p class="indicator-input">
            <%= f.select(:unit) do %>
                <% [['Hours', 0], ['Days', 1], ['Yuan', 2]].each do |c| -%>
                    <%= content_tag(:option, c.first, value: c.last) %>
                <% end %>
            <% end %>
          </p>
        </div>
        <div class="input-item">
          <p class="indicator-label"><%= f.label :'Marks per period' %>
            <span class="required">*</span>
          </p>
          <p class="indicator-input">
            <%= f.select(:marksperperiod) do %>
                <% [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]].each do |c| -%>
                    <%= content_tag(:option, c.first, value: c.last) %>
                <% end %>
            <% end %>
          </p>
        </div>
        <div class="input-item">
          <p class="indicator-label"><%= f.label :'Objective indicator' %>
            <span class="required">*</span>
          </p>
          <p class="indicator-input">
            <%= f.check_box :isobjective %>
          </p>
        </div>
        <div class="input-item">
          <p class="indicator-label"><%= f.label :'Interpretation' %>
            <span class="required">*</span>
          </p>
          <p class="indicator-input">
            <%= f.text_area :interpretation %>
          </p>
        </div>
        <div class="input-item">
          <%= f.submit 'Save' %>
        </div>
    <% end %>
  </div>
  <div class="indicator-gener-right indicator-gener"></div>
</div>
<div class="features">
  <%= render 'shared/features' %>
</div>
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'basic', :plugin => 'kpi' %>
    <%= stylesheet_link_tag 'indicator_create', :plugin => 'kpi' %>
<% end %>

app/views/indicators/index.html.erb
<div class="content">
  <div class="banner-tool">
    <h2 class="left">Indicators</h2>
    <div class="right">
      <%= render 'tools'  %>
    </div>
  </div>
  <table width="100%" style="border-collapse: collapse" border="1">
    <thead>
    <tr>
      <th>名称</th>
      <th>描述</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @indicators.each do |indicator| %>
        <tr>
          <td>
            <%= link_to indicator.name, edit_indicator_path(indicator) %>
          </td>
          <td>
            <%= indicator.interpretation %>
          </td>
          <td>
                <%= link_to "复制", indicator_path(indicator) %>
                <%= link_to "删除", indicator_path(indicator),
                            method: :delete,
                            data: { confirm: 'Are you sure?' }%>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="features">
  <%= render 'shared/features' %>
</div>
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'basic', :plugin => 'kpi' %>
<% end %>

app/views/indicators/new.html.erb
<div class="content">
  <h2>Add new performance indicator</h2>
  <div>
    <%= render 'shared/form' %>
  </div>
</div>
<div class="features">
  <%= render 'shared/features' %>
</div>
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'basic', :plugin => 'kpi' %>
    <%= stylesheet_link_tag 'indicator_create', :plugin => 'kpi' %>
<% end %>

app/views/indicators/show.html.erb
<div class="show">
  <div class="content">
    <h2>Edit show</h2>
    <%= render 'shared/form'  %>
  </div>

  <div class="features">
    <%= render 'shared/features' %>
  </div>
</div>
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'basic', :plugin => 'kpi' %>
    <%= stylesheet_link_tag 'indicator_create', :plugin => 'kpi' %>
<% end %>

app/views/shared/_features.html.erb
<div>
  <h3>管理</h3>
  <ul>
    <li>
      <%= link_to (t 'Performance_indicator'),indicators_path %>
    </li>
    <li>
      <%= link_to (t 'KPI_patterns'),indicators_path %>
    </li>
    <li>
      <%= link_to (t 'Calculation_periods'),indicators_path %>
    </li>
    <li>
      <%= link_to (t 'Through_indicators'),indicators_path %>
    </li>
    <li>
      <%= link_to (t 'Surcharges'),indicators_path %>
    </li>
  </ul>
  <h3>报告</h3>
  <ul>
    <li>
      <%= link_to (t 'Salary_report'),indicators_path %>
    </li>
    <li>
      <%= link_to (t 'Effectiveness_shift_report'),indicators_path %>
    </li>
    <li>
      <%= link_to (t 'Unmotivated_employees'),indicators_path %>
    </li>
  </ul>
  <h3>分析</h3>
  <ul>
    <li>
      <%= link_to (t 'Salary_analytics'),indicators_path %>
    </li>
  </ul>
</div>

app/views/shared/_form.erb
<div class="indicator-gener-left indicator-gener">
  <%= form_for :indicator, url: indicators_path do |f| %>
      <div class="input-item">
        <p class="indicator-label"><%= f.label :"Indicator name" %>
          <span class="required">*</span>
        </p>
        <p class="indicator-input">
          <%= f.text_field :name %>
        </p>
      </div>
      <div class="input-item">
        <p class="indicator-label"><%= f.label :'Actual values input type' %>
          <span class="required">*</span>
        </p>
        <p class="indicator-input">
          <%= f.select(:inputtype) do %>
              <% [['Direct input', 0], ['Exact values from the interpretation matrix', 1]].each do |c| -%>
                  <%= content_tag(:option, c.first, value: c.last) %>
              <% end %>
          <% end %>
        </p>
      </div>
      <div class="input-item">
        <p class="indicator-label"><%= f.label :'Category' %>
          <span class="required">*</span>
        </p>
        <p class="indicator-input">
          <%= f.select(:category) do %>
              <% [['Common indicator', 0]].each do |c| -%>
                  <%= content_tag(:option, c.first, value: c.last) %>
              <% end %>
          <% end %>
        </p>
      </div>
      <div class="input-item">
        <p class="indicator-label"><%= f.label :'Indicator unit of measurement ' %>
          <span class="required">*</span>
        </p>
        <p class="indicator-input">
          <%= f.select(:unit) do %>
              <% [['Hours', 0], ['Days', 1], ['Yuan', 2]].each do |c| -%>
                  <%= content_tag(:option, c.first, value: c.last) %>
              <% end %>
          <% end %>
        </p>
      </div>
      <div class="input-item">
        <p class="indicator-label"><%= f.label :'Marks per period' %>
          <span class="required">*</span>
        </p>
        <p class="indicator-input">
          <%= f.select(:marksperperiod) do %>
              <% [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]].each do |c| -%>
                  <%= content_tag(:option, c.first, value: c.last) %>
              <% end %>
          <% end %>
        </p>
      </div>
      <div class="input-item">
        <p class="indicator-label"><%= f.label :'Objective indicator' %>
          <span class="required">*</span>
        </p>
        <p class="indicator-input">
          <%= f.check_box :isobjective %>
        </p>
      </div>
      <div class="input-item">
        <p class="indicator-label"><%= f.label :'Interpretation' %>
          <span class="required">*</span>
        </p>
        <p class="indicator-input">
          <%= f.text_area :interpretation %>
        </p>
      </div>

      <div class="input-item">
        <%= f.submit 'Create' %>
      </div>
  <% end %>
</div>
<div class="indicator-gener-right indicator-gener"></div>